"""empty message

Revision ID: 89cc2df70ead
Revises: e22df924a413
Create Date: 2022-08-15 20:19:03.272194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89cc2df70ead'
down_revision = 'e22df924a413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('date', sa.DateTime(), nullable=False))
    op.drop_column('show', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('show', 'date')
    # ### end Alembic commands ###
