"""empty message

Revision ID: e0bdf60da77b
Revises: b2b4c7ad37a8
Create Date: 2022-08-12 22:19:39.663571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0bdf60da77b'
down_revision = 'b2b4c7ad37a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('venue', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('artist', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_time', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['artist'], ['Artist.id'], name='show_artist_fkey'),
    sa.ForeignKeyConstraint(['venue'], ['Venue.id'], name='show_venue_fkey'),
    sa.PrimaryKeyConstraint('id', name='show_pkey')
    )
    # ### end Alembic commands ###
